runtime: python38
# For first deployment to a new project, need to leave service blank, then can deploy with desired service name
# service: data-simulation-experience
# TBD need to fill out!


#instance_class: F2
